### ISSUE TITLE
Possibility to delete cue points

### ISSUE THREAD

**Issue by Zeratoxx** [soundcrowd/soundcrowd#83]
Is it possible to delete cue points?  
If so, I couldn't find it.  
If not, would love to see this feature :)

Thanks for the app so far!

**Comment by 0xf4b1** [comment]
In the main player window with the waveform, you can long press on the points to open a menu that allows you to add a description or delete them. The cue list window does not have these options yet but this is something I would also like to have in the next version

**Comment by Zeratoxx** [comment]
Thank you @0xf4b1 for your answer!

That said, this long press menu is only for soundcloud songs I guess? There is no waveform at Spotify songs as far as I see.

**Comment by 0xf4b1** [comment]
Oh yes that's true unfortunately, waveforms are only supported for soundcloud and are being generated for local music files. One more reason why this functionality should also be accessible from the cue points view
